(function(g){var window=this;var Lpa=function(a,b){return g.Wb(a,b)},x5=function(a,b,c){a.w.set(b,c)},y5=function(a){x5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.A)()).toString(36));
return a},z5=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.Wm(a.w,b,c)},Mpa=function(a,b){var c=[];
g.aj(b,function(d){try{var e=g.Gn.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Fn(e)&&c.push(d)},a);
return c},Npa=function(a,b){var c=Mpa(a,b);
(0,g.z)(c,function(d){g.Gn.prototype.remove.call(this,d)},a)},A5=function(a){if(a.gd){if(a.gd.locationOverrideToken)return{locationOverrideToken:a.gd.locationOverrideToken};
if(null!=a.gd.latitudeE7&&null!=a.gd.longitudeE7)return{latitudeE7:a.gd.latitudeE7,longitudeE7:a.gd.longitudeE7}}return null},Opa=function(a,b){g.$a(a,b)||a.push(b)},B5=function(a){var b=0,c;
for(c in a)b++;return b},C5=function(a,b){var c=b instanceof g.Bc?b:g.Gc(b,/^data:image\//i.test(b));
a.src=g.Cc(c)},D5=function(){},Ppa=function(a){try{return g.u.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Qpa=function(a){if(a.sd&&"function"==typeof a.sd)return a.sd();
if("string"===typeof a)return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Rb(a)},Rpa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||"string"===typeof a)(0,g.z)(a,b,void 0);else{if(a.fe&&"function"==typeof a.fe)var c=a.fe();else if(a.sd&&"function"==typeof a.sd)c=void 0;else if(g.La(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Sb(a);d=Qpa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Spa=function(a,b,c,d){var e=new g.Km(null,void 0);
a&&g.Lm(e,a);b&&g.Mm(e,b);c&&g.Nm(e,c);d&&(e.u=d);return e},E5=function(a,b){g.Io[a]=!0;
var c=g.Go();c&&c.publish.apply(c,arguments);g.Io[a]=!1},F5=function(a){try{var b=(0,g.ay)(),c=(0,g.$x)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Tpa=function(){var a=(0,g.$x)();
a&&Npa(a,a.o.tf(!0))},G5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.w=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Hm;this.o=this.u="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Upa(this,a.capabilities||""),Vpa(this,a.experiments||""),this.u=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},Upa=function(a,b){a.capabilities.clear();
(0,g.Zd)(b.split(","),g.Qa(Lpa,Wpa)).forEach(function(c){a.capabilities.add(c)})},Vpa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},H5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},I5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},J5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Xpa=function(a){return new H5(a)},K5=function(a){return g.Ka(a)?(0,g.ie)(a,Xpa):[]},L5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},M5=function(a){return g.Ka(a)?"["+(0,g.ie)(a,L5).join(",")+"]":"null"},N5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Ypa=function(a){return(0,g.ie)(a,function(b){return{key:b.id,
name:b.name}})},O5=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},P5=function(a,b){return g.Xa(a,function(c){return I5(c,b)})},Q5=function(){var a=g.cy("yt-remote-connected-devices")||[];
g.qb(a);return a},Zpa=function(a){if(g.ab(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ie)(a,function(d,e){return 0==e?d:d.substring(c.length)})},R5=function(a){g.by("yt-remote-connected-devices",a,86400)},T5=function(){if(S5)return S5;
var a=g.cy("yt-remote-device-id");a||(a=N5(),g.by("yt-remote-device-id",a,31536E3));for(var b=Q5(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return S5=d},U5=function(){var a=Q5(),b=T5();
g.$a(a,b);g.vL()&&g.sb(a,b);a=Zpa(a);if(g.ab(a))try{g.wr("remote_sid")}catch(c){}else try{g.vr("remote_sid",a.join(","),-1)}catch(c){}},V5=function(){return g.cy("yt-remote-session-browser-channel")},W5=function(){return g.cy("yt-remote-local-screens")||[]},X5=function(){g.by("yt-remote-lounge-token-expiration",!0,86400)},$pa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ie)(W5(),function(d){return d.loungeToken}),c=(0,g.ie)(a,function(d){return d.loungeToken});
(0,g.dh)(c,function(d){return!g.$a(b,d)})&&X5();
g.by("yt-remote-local-screens",a,31536E3)},aqa=function(a,b){g.by("yt-remote-session-browser-channel",a);
g.by("yt-remote-session-screen-id",b);var c=Q5(),d=T5();g.$a(c,d)||c.push(d);R5(c);U5()},Y5=function(a){a||(F5("yt-remote-session-screen-id"),F5("yt-remote-session-video-id"));
U5();a=Q5();g.db(a,T5());R5(a)},$5=function(){if(!Z5){var a=g.Qn();
a&&(Z5=new g.An(a))}return Z5?!!Z5.get("yt-remote-use-staging-server"):!1},a6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},b6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},d6=function(a){a.length?c6(a.shift(),function(){d6(a)}):e6()},bqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},c6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},e6=function(){var a=b6();
a&&a(!1,"No cast extension found")},f6=function(){if(cqa){var a=2,b=b6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;c6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",e6,c)}},dqa=function(){f6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);d6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},g6=function(a,b,c){g.E.call(this);
this.C=null!=c?(0,g.x)(a,c):a;this.Xc=b;this.B=(0,g.x)(this.PC,this);this.o=!1;this.u=0;this.w=this.Fa=null;this.A=[]},h6=function(a){if(g.u.JSON)try{return g.u.JSON.parse(a)}catch(b){}return Ppa(a)},i6=function(){},j6=function(){},k6=function(){},m6=function(a){return(a=l6(a))?new ActiveXObject(a):new XMLHttpRequest},l6=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},n6=function(a,b,c,d){this.o=a;
this.w=b;this.F=c;this.C=d||1;this.A=45E3;this.ea=new g.KZ(this);this.u=new g.gl;this.u.setInterval(250)},p6=function(a,b,c){a.hi=1;
a.Zf=y5(b.clone());a.Ah=c;a.B=!0;o6(a,null)},q6=function(a,b,c,d,e){a.hi=1;
a.Zf=y5(b.clone());a.Ah=null;a.B=c;e&&(a.Lz=!1);o6(a,d)},o6=function(a,b){a.Oi=(0,g.A)();
r6(a);a.Hg=a.Zf.clone();z5(a.Hg,"t",a.C);a.nl=0;a.yc=a.o.Bp(a.o.Wk()?b:null);0<a.eq&&(a.Qn=new g.jl((0,g.x)(a.IA,a,a.yc),a.eq));a.ea.ha(a.yc,"readystatechange",a.LL);var c=a.gh?g.bc(a.gh):{};a.Ah?(a.yo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.yc.send(a.Hg,a.yo,a.Ah,c)):(a.yo="GET",a.Lz&&!g.Md&&(c.Connection="close"),a.yc.send(a.Hg,a.yo,null,c));a.o.we(1)},y6=function(a,b,c){for(var d=!0;!a.Sg&&a.nl<c.length;){var e=eqa(a,c);
if(e==s6){4==b&&(a.qg=4,t6(15),d=!1);break}else if(e==u6){a.qg=4;t6(16);d=!1;break}else v6(a,e)}4==b&&0==c.length&&(a.qg=1,t6(17),d=!1);a.xe=a.xe&&d;d||(w6(a),x6(a))},eqa=function(a,b){var c=a.nl,d=b.indexOf("\n",c);
if(-1==d)return s6;c=Number(b.substring(c,d));if(isNaN(c))return u6;d+=1;if(d+c>b.length)return s6;var e=b.substr(d,c);a.nl=d+c;return e},B6=function(a,b){a.Oi=(0,g.A)();
r6(a);var c=b?window.location.hostname:"";a.Hg=a.Zf.clone();x5(a.Hg,"DOMAIN",c);x5(a.Hg,"t",a.C);try{a.De=new ActiveXObject("htmlfile")}catch(n){w6(a);a.qg=7;t6(22);x6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in z6)k=z6[l];else if(l in A6)k=z6[l]=A6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
z6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Uc(g.sc("b/12014412"),d+"</body></html>");a.De.open();a.De.write(g.Pc(c));a.De.close();a.De.parentWindow.m=(0,g.x)(a.bL,a);a.De.parentWindow.d=(0,g.x)(a.Ty,a,!0);a.De.parentWindow.rpcClose=(0,g.x)(a.Ty,a,!1);c=a.De.createElement("DIV");a.De.parentWindow.document.body.appendChild(c);d=g.Fc(a.Hg.toString());d=g.ad(g.Dc(d));d=g.Uc(g.sc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Vc(c,d);a.o.we(1)},r6=function(a){a.Vs=(0,g.A)()+a.A;
C6(a,a.A)},C6=function(a,b){if(null!=a.dj)throw Error("WatchDog timer not null");
a.dj=D6((0,g.x)(a.jL,a),b)},E6=function(a){a.dj&&(g.u.clearTimeout(a.dj),a.dj=null)},x6=function(a){a.o.Pv()||a.Sg||a.o.Hn(a)},w6=function(a){E6(a);
g.Ei(a.Qn);a.Qn=null;a.u.stop();g.MZ(a.ea);if(a.yc){var b=a.yc;a.yc=null;b.abort();b.dispose()}a.De&&(a.De=null)},v6=function(a,b){try{a.o.Ny(a,b),a.o.we(4)}catch(c){}},G6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;F6(a,b,function(k){k?c(!0):g.u.setTimeout(function(){G6(a,b,c,d,f)},f)})}},F6=function(a,b,c){var d=new Image;
d.onload=function(){try{H6(d),c(!0)}catch(e){}};
d.onerror=function(){try{H6(d),c(!1)}catch(e){}};
d.onabort=function(){try{H6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{H6(d),c(!1)}catch(e){}};
g.u.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
C5(d,a)},H6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},I6=function(a){this.o=a;
this.u=new i6},K6=function(a){var b=J6(a.o,a.pj,"/mail/images/cleardot.gif");
y5(b);G6(b.toString(),5E3,(0,g.x)(a.OB,a),3,2E3);a.we(1)},M6=function(a){var b=a.o.H;
if(null!=b)t6(5),b?(t6(11),L6(a.o,a,!1)):(t6(12),L6(a.o,a,!0));else if(a.Ed=new n6(a,void 0,void 0,void 0),a.Ed.gh=a.bq,b=a.o,b=J6(b,b.Wk()?a.Rj:null,a.cq),t6(5),!g.Kd||g.od(10))z5(b,"TYPE","xmlhttp"),q6(a.Ed,b,!1,a.Rj,!1);else{z5(b,"TYPE","html");var c=a.Ed;a=!!a.Rj;c.hi=3;c.Zf=y5(b.clone());B6(c,a)}},N6=function(a){g.wk.call(this);
this.headers=new g.Hm;this.P=a||null;this.w=!1;this.U=this.o=null;this.Z=this.H="";this.C=0;this.A="";this.B=this.da=this.G=this.T=!1;this.F=0;this.J=null;this.ba="";this.K=this.V=!1},fqa=function(a){return g.Kd&&g.nd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},gqa=function(a){return"content-type"==a.toLowerCase()},Q6=function(a,b){a.w=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.A=b;a.C=5;O6(a);P6(a)},O6=function(a){a.T||(a.T=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},iqa=function(a){if(a.w&&"undefined"!=typeof g.SZ)if(a.U[1]&&4==R6(a)&&2==a.getStatus())S6(a,"Local request error detected and ignored");
else if(a.G&&4==R6(a))g.hl(a.Rv,0,a);else if(a.dispatchEvent("readystatechange"),4==R6(a)){S6(a,"Request complete");a.w=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.zf(1,String(a.H));if(!f&&g.u.self&&g.u.self.location){var k=g.u.self.location.protocol;f=k.substr(0,k.length-1)}e=!hqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<R6(a)?a.o.statusText:""}catch(m){l=""}a.A=l+" ["+a.getStatus()+"]";O6(a)}}finally{P6(a)}}},P6=function(a,b){if(a.o){jqa(a);
var c=a.o,d=a.U[0]?g.Ha:null;a.o=null;a.U=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},jqa=function(a){a.o&&a.K&&(a.o.ontimeout=null);
a.J&&(g.u.clearTimeout(a.J),a.J=null)},R6=function(a){return a.o?a.o.readyState:0},T6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},S6=function(a,b){return b+" ["+a.Z+" "+a.H+" "+a.getStatus()+"]"},U6=function(a,b,c){this.o=1;
this.u=[];this.A=[];this.B=new i6;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},kqa=function(a,b){this.o=a;
this.map=b;this.context=null},lqa=function(a){g.Yj.call(this,"statevent",a)},mqa=function(a,b){g.Yj.call(this,"timingevent",a);
this.size=b},nqa=function(a){g.Yj.call(this,"serverreachability",a)},qqa=function(a){oqa(a);
if(3==a.o){var b=a.Bk++,c=a.nm.clone();x5(c,"SID",a.w);x5(c,"RID",b);x5(c,"TYPE","terminate");V6(a,c);b=new n6(a,a.w,b,void 0);b.hi=2;b.Zf=y5(c.clone());C5(new Image,b.Zf.toString());b.Oi=(0,g.A)();r6(b)}pqa(a)},rqa=function(a){a.iC(1,0);
a.nm=J6(a,null,a.Zp);W6(a)},oqa=function(a){a.fg&&(a.fg.abort(),a.fg=null);
a.Tb&&(a.Tb.cancel(),a.Tb=null);a.uf&&(g.u.clearTimeout(a.uf),a.uf=null);X6(a);a.zd&&(a.zd.cancel(),a.zd=null);a.mg&&(g.u.clearTimeout(a.mg),a.mg=null)},sqa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new kqa(a.qH++,b));2!=a.o&&3!=a.o||W6(a)},W6=function(a){a.zd||a.mg||(a.mg=D6((0,g.x)(a.Sy,a),0),a.Yh=0)},uqa=function(a,b){if(1==a.o){if(!b){a.Bk=Math.floor(1E5*Math.random());
var c=a.Bk++,d=new n6(a,"",c,void 0);d.gh=null;var e=Y6(a),f=a.nm.clone();x5(f,"RID",c);x5(f,"CVER","1");V6(a,f);p6(d,f,e);a.zd=d;a.o=2}}else 3==a.o&&(b?tqa(a,b):0==a.u.length||a.zd||tqa(a))},tqa=function(a,b){if(b)if(6<a.Tg){a.u=a.A.concat(a.u);
a.A.length=0;var c=a.Bk-1;var d=Y6(a)}else c=b.F,d=b.Ah;else c=a.Bk++,d=Y6(a);var e=a.nm.clone();x5(e,"SID",a.w);x5(e,"RID",c);x5(e,"AID",a.wi);V6(a,e);c=new n6(a,a.w,c,a.Yh+1);c.gh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.zd=c;p6(c,e,d)},V6=function(a,b){if(a.Uc){var c=a.Uc.kv();
c&&g.Lb(c,function(d,e){x5(b,e,d)})}},Y6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Tg&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.Tg?e:f-d;try{g.Lb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.u.splice(0,b));
return c.join("&")},vqa=function(a){a.Tb||a.uf||(a.F=1,a.uf=D6((0,g.x)(a.Ry,a),0),a.Sh=0)},Z6=function(a){if(a.Tb||a.uf||3<=a.Sh)return!1;
a.F++;a.uf=D6((0,g.x)(a.Ry,a),wqa(a,a.Sh));a.Sh++;return!0},L6=function(a,b,c){a.wo=c;
a.Le=b.Gf;a.C||rqa(a)},X6=function(a){null!=a.Xg&&(g.u.clearTimeout(a.Xg),a.Xg=null)},wqa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$6=function(a,b){if(2==b||9==b){var c=null;
a.Uc&&(c=null);var d=(0,g.x)(a.uM,a);c||(c=new g.Km("//www.google.com/images/cleardot.gif"),y5(c));F6(c.toString(),1E4,d)}else t6(2);xqa(a,b)},xqa=function(a,b){a.o=0;
a.Uc&&a.Uc.xu(b);pqa(a);oqa(a)},pqa=function(a){a.o=0;
a.Le=-1;if(a.Uc)if(0==a.A.length&&0==a.u.length)a.Uc.vp();else{g.gb(a.A);var b=g.gb(a.u);a.A.length=0;a.u.length=0;a.Uc.vp(b)}},J6=function(a,b,c){var d=g.Sm(c);
if(""!=d.o)b&&g.Mm(d,b+"."+d.o),g.Nm(d,d.B);else{var e=window.location;d=Spa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Cj&&g.Lb(a.Cj,function(f,k){x5(d,k,f)});
x5(d,"VER",a.Tg);V6(a,d);return d},D6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.u.setTimeout(function(){a()},b)},t6=function(a){a7.dispatchEvent(new lqa(a7,a))},yqa=function(){},zqa=function(){this.o=[];
this.u=[]},Aqa=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.E.call(this);
this.o=new g.J(this.SK,0,this);g.H(this,this.o);this.Xc=5E3;this.u=0;if(g.Ma(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.w=a},c7=function(a,b,c){this.J=a;
this.C=b;this.w=new g.zn;this.u=new b7(this.VL,this);this.o=null;this.ib=!1;this.B=null;this.H="";this.G=this.A=0;this.F=[];this.K=c||!1},Bqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.wo,sessionId:a.o.w,arrayId:a.o.wi}},Cqa=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&uqa(a.o),qqa(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},Dqa=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.zf(4,a))||"";b&&(this.port=":"+b);this.domain=g.Af(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.Lf(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.A,d,!0),onError:g.Qa(a.w,e),Sd:g.Qa(a.B,e)};c&&(a.wb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Bp(b,a)},Hqa=function(){var a=Eqa;
Fqa();h7.push(a);Gqa(h7)},i7=function(a,b){Fqa();
var c=h7,d=Iqa(a,String(b));g.ab(c)?Jqa(d):(Gqa(c),(0,g.z)(c,function(e){e(d)}))},Fqa=function(){h7||(h7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",h7,void 0))},Jqa=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},Gqa=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},Iqa=function(a,b){var c=((0,g.A)()-Kqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.O.call(this);
this.F=a;this.o=[]},Lqa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},Mqa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Zd)(a.o,function(f){return!!O5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Lqa(a,b[d])||c;return c},Nqa=function(a,b){var c=a.o.length;
a.o=(0,g.Zd)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.O.call(this);
this.C=a;this.B=b;this.w=c;this.A=d;this.u=0;this.o=null;this.Fa=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.w=a;this.u=NaN;o7(this);this.info("Initializing with "+M5(this.o))},Oqa=function(a){if(a.o.length){var b=(0,g.ie)(a.o,function(d){return d.id}),c=f7(a.w,"/pairing/get_lounge_token_batch");
g7(a.w,c,{screen_ids:b.join(",")},(0,g.x)(a.ZC,a),(0,g.x)(a.YC,a))}},o7=function(a){var b=K5(W5());
b=(0,g.Zd)(b,function(c){return!c.uuid});
return Mqa(a,b)},q7=function(a,b){$pa((0,g.ie)(a.o,J5));
b&&X5()},s7=function(a,b){g.O.call(this);
this.C=b;var c=g.cy("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.o=d;this.B=a;this.w=this.A=NaN;this.u=null;r7("Initialized with "+g.Bj(this.o))},Pqa=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(B5(b)!=B5(a.o))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.Bj(a.o)),a.o=b,a.R("screenChange"));Qqa(a)},u7=function(a){isNaN(a.w)||g.Fo(a.w);
a.w=g.zo((0,g.x)(a.ds,a),0<a.A&&a.A<(0,g.A)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},Rqa=function(a){var b={};
(0,g.z)(a.C(),function(c){c.token?b[c.token]=c.id:this.Nb("Requesting availability of screen w/o lounge token.")});
return b},Qqa=function(a){a=g.Sb(g.Mb(a.o,function(b){return b}));
g.qb(a);a.length?g.by("yt-remote-online-screen-ids",a.join(","),60):F5("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.w=null;this.A=[];this.B={};Sqa(this)},Uqa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.Od();if(k=(c?P5(k,c):null)||P5(k,b)){k.uuid=b;var l=w7(a,k);Pqa(a.u,l,function(m){e(m?l:null)})}else c?Tqa(a,c,(0,g.x)(function(m){var n=w7(this,new H5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Pqa(this.u,n,function(q){e(q?n:null)})},a),f):e(null)},Vqa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},Tqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={wb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Bp(f7(a.C,"/pairing/get_lounge_token_batch"),e)},Wqa=function(a){a.o=a.w.Od();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+M5(a.o))},Sqa=function(a){x7(a);
a.w=new p7(a.C);a.w.subscribe("screenChange",(0,g.x)(a.gD,a));Wqa(a);a.A=K5(g.cy("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+M5(a.A));a.u=new s7(a.C,(0,g.x)(a.Od,a,!0));a.u.subscribe("screenChange",(0,g.x)(function(){this.R("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=P5(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.by("yt-remote-automatic-screen-cache",(0,g.ie)(a.A,J5)));x7(a);a.B[b.uuid]=b.id;g.by("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.cy("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.O.call(this);
this.U=c;this.H=a;this.u=b;this.w=null},z7=function(a,b){i7(a.U,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.dN,this);this.B=(0,g.x)(this.uL,this);this.A=g.zo((0,g.x)(function(){Xqa(this,null)},this),12E4)},Yqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Bj(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.x)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.Bj(b))},Xqa=function(a,b){g.Fo(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.w||a.w.id!=b){var c=(0,g.x)(a.Jn,a),d=(0,g.x)(a.Rd,a);a.Jv(b,c,d,5)}}else a.Rd(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.J="";this.P=c;this.B=null;this.F=g.Ha;this.C=NaN;this.K=(0,g.x)(this.gN,this);this.o=g.Ha},Zqa=function(a){a.o=a.H.OA(a.J,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Ha;
this.Jn(b)},a),(0,g.x)(function(b){this.o=g.Ha;
this.Rd(b)},a))},$qa=function(a){var b={};
b.pairingCode=a.J;b.theme=a.P;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}$5()&&(b.env_useStageMdx=1);return g.Hf(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.zo((0,g.x)(this.xi,this,null),150)},D7=function(a,b,c,d){g.O.call(this);
this.u=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.w=[];this.A=(0,g.x)(this.aK,this)},ara=function(a,b){return b?g.Xa(a.w,function(c){return I5(b,c.label)},a):null},E7=function(a){i7("Controller",a)},Eqa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.w.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.Ei(a.o),(a.o=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.u):a.R("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.Qy,a,b)),b.w?a.R("yt-remote-cast2-session-change",b.w):c&&a.o.xi(null)):a.R("yt-remote-cast2-session-change",null))},bra=function(a){var b=a.u.NA(),c=a.o&&a.o.u;
a=(0,g.ie)(b,function(d){c&&I5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=ara(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},hra=function(a,b,c,d,e,f,k){cra()?dra(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?era(a,c):(window.__onGCastApiAvailable=function(l,m){l?era(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),F5("yt-remote-cast-available"),F5("yt-remote-cast-receiver"),fra(),c(!1))},d?g.Qo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?dqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?e6():(f6(),d6(gra.map(bqa))))):H7("Cannot initialize because not running Chrome")},fra=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);ira(!1);g.Lo(M7);M7.length=0},N7=function(){return!!g.cy("yt-remote-cast-installed")},jra=function(){var a=g.cy("yt-remote-cast-receiver");
return a?a.friendlyName:null},kra=function(){H7("clearCurrentReceiver");
F5("yt-remote-cast-receiver")},lra=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.Ko("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},cra=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Hs||a},mra=function(a,b){L7().init(a,b)},dra=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.by("yt-remote-cast-available",f);E5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.by("yt-remote-cast-receiver",f);E5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.by("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+L5(f));
f||F5("yt-remote-cast-receiver");E5("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},era=function(a,b){K7(!0);
I7(!1);mra(a,function(c){c?(ira(!0),g.No("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),F5("yt-remote-cast-available"),F5("yt-remote-cast-receiver"),fra());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.by("yt-remote-cast-installed",a)},O7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},ira=function(a){H7("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.F=0;this.o=null;this.hasNext=this.Me=!1;this.H=this.G=this.u=this.A=0;this.w=NaN;this.B=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Me=!1;a.hasNext=!1;a.F=0;a.C=(0,g.A)();a.A=0;a.u=0;a.G=0;a.H=0;a.w=NaN;a.B=!1},T7=function(a){return 1==a.playerState?((0,g.A)()-a.C)/1E3:0},U7=function(a,b){a.F=b;
a.C=(0,g.A)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.A)()-a.C)/1E3+a.F;
case -1E3:return 0}return a.F},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.o);b.hasPrevious=a.Me;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.C;b.seekableStart=a.A;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.H;b.liveIngestionTime=a.w;return b},Z7=function(a,b){g.O.call(this);
this.o=0;this.A=a;this.C=[];this.B=new zqa;this.w=this.u=null;this.H=(0,g.x)(this.YH,this);this.F=(0,g.x)(this.Ek,this);this.G=(0,g.x)(this.XH,this);this.J=(0,g.x)(this.kI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ys,this),nra(this))):c=3;0!=c&&(b?this.Ys(c):g.zo((0,g.x)(function(){this.Ys(c)},this),0));
var d=lra();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},$7=function(a){return new R7(a.A.getPlayerContextData())},nra=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Qa(this.XJ,b),this))},a)},ora=function(a){(0,g.z)(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){var c=a.B;
50>c.o.length+c.u.length&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.A.sendMessage(b,c)},b8=function(a,b){ora(a);
a.A.setPlayerContextData(X7(b));nra(a)},Y7=function(a,b){a.w&&(a.w.removeUpdateListener(a.H),a.w.removeMediaListener(a.F),a.Ek(null));
a.w=b;a.w&&(i7("CP","Setting cast session: "+a.w.sessionId),a.w.addUpdateListener(a.H),a.w.addMediaListener(a.F),a.w.media.length&&a.Ek(a.w.media[0]))},pra=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.x)(function(d){this.Nb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Nb("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.O.call(this);
this.B=NaN;this.K=!1;this.G=this.F=this.H=this.J=NaN;this.U=[];this.A=this.C=this.w=this.Sa=this.o=null;this.T=a;this.U.push(g.$q(window,"beforeunload",(0,g.x)(this.SC,this)));this.u=[];this.Sa=new R7;this.P=b.id;this.o=qra(this,c);this.o.subscribe("handlerOpened",this.cI,this);this.o.subscribe("handlerClosed",this.ZH,this);this.o.subscribe("handlerError",this.aI,this);this.o.subscribe("handlerMessage",this.bI,this);Dqa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Sa.videoId;
g.vL()&&g.by("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},qra=function(a,b){return new c7(f7(a.T,"/bc"),b)},h8=function(a,b){a.R("proxyStateChange",b)},rra=function(a){a.B=g.zo((0,g.x)(function(){g8("Connecting timeout");
this.Wh(1)},a),2E4)},i8=function(a){g.Fo(a.B);
a.B=NaN},j8=function(a){g.Fo(a.J);
a.J=NaN},sra=function(a){k8(a);
a.H=g.zo((0,g.x)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.Fo(a.H);
a.H=NaN},ura=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.Hv()&&a.Sa.reset(),h8(a,1),l8(a,"getNowPlaying"),tra(a)):a.Wh(1)},vra=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Sa.videoId&&(g.Zb(b.params)?a.Sa.o=null:a.Sa.o=b.params,a.R("remotePlayerChange"))},wra=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Sa.listId=b.params.listId||a.Sa.listId;W7(a.Sa,c,d);a.R("remoteQueueChange")},yra=function(a,b){b.params=b.params||{};
wra(a,b);xra(a,b);a.R("autoplayDismissed")},xra=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Sa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Sa.playerState&&(c=-1E3);a.Sa.playerState=c;c=Number(b.params.loadedTime);a.Sa.H=isNaN(c)?0:c;c=Number(b.params.duration);a.Sa.G=isNaN(c)?0:c;c=a.Sa;var d=Number(b.params.liveIngestionTime);c.w=d;c.B=isNaN(d)?!1:!0;c=a.Sa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.A=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Sa.playerState?sra(a):k8(a);a.R("remotePlayerChange")},zra=function(a,b){if(-1E3!=
a.Sa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Sa.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Sa,isNaN(c)?0:c);a.R("remotePlayerChange")}},Ara=function(a,b){var c="true"==b.params.muted;
a.Sa.volume=parseInt(b.params.volume,10);a.Sa.muted=c;a.R("remotePlayerChange")},Bra=function(a,b){a.C=b.params.videoId;
a.R("nowAutoplaying",parseInt(b.params.timeout,10))},Cra=function(a,b){var c="true"==b.params.hasNext;
a.Sa.Me="true"==b.params.hasPrevious;a.Sa.hasNext=c;a.R("previousNextChange")},tra=function(a){g.Fo(a.G);
a.G=g.zo((0,g.x)(a.Wh,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.Bj(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.Wc=a;this.u=[];this.u.push(this.Wc.$_s("screenChange",(0,g.x)(this.bN,this)));this.u.push(this.Wc.$_s("onlineScreenChange",(0,g.x)(this.BJ,this)))},Hra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.ro("MDX_CONFIG")||b;Tpa();U5();n8||(n8=new e7(b?b.loungeApiHost:void 0),$5()&&(n8.o="/api/loungedev"));o8||(o8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",o8,void 0));Dra();var c=p8();if(!c){var d=new v7(n8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);hra(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){E5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.Bj(b)),s8.push(g.Ko("yt-remote-cast2-availability-change",function(){E5("yt-remote-receiver-availability-change")})),s8.push(g.Ko("yt-remote-cast2-receiver-selected",function(){t8(null);
E5("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.Ko("yt-remote-cast2-receiver-resumed",function(){E5("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.Ko("yt-remote-cast2-session-change",Era)),s8.push(g.Ko("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),kra())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.sp("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.Bj(a)),Fra(a),c.start(),q8()||Gra())},Jra=function(){var a=Ira();
N7()&&g.cy("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Ira=function(){var a=p8().Wc.$_gos();
var b=w8();b&&x8()&&(O5(a,b)||a.push(b));return Ypa(a)},y8=function(){var a=Kra();
!a&&N7()&&jra()&&(a={key:"cast-selector-receiver",name:jra()});return a},Kra=function(){var a=Ira(),b=w8();
b||(b=u8());return g.Xa(a,function(c){return b&&I5(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().Od();return P5(b,a)},Era=function(a){r8("remote.onCastSessionChange_: "+L5(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.w("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.w("yt.mdx.remote.currentScreenId_")},Lra=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},Mra=function(){return g.w("yt.mdx.remote.connectData_")},t8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.w("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||Lra("");g.Ga("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.z)(o8,function(c){c(a)}),o8.length=0);
b&&!a?E5("yt-remote-connection-change",!1):!b&&a&&E5("yt-remote-connection-change",!0)},u8=function(){var a=g.vL();
if(!a)return null;var b=p8().Od();return P5(b,a)},A8=function(a,b){w8()&&w8();
if(E8)F8=a;else{Lra(a.id);var c=new f8(n8,a,v8());c.connect(b,Mra());c.subscribe("beforeDisconnect",function(d){E5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&B8(null)});
B8(c)}},Gra=function(){var a=u8();
a?(r8("Resume connection to: "+L5(a)),A8(a,0)):(Y5(),kra(),r8("Skipping connecting because no session screen found."))},Dra=function(){var a=v8();
if(g.Zb(a)){a=T5();var b=g.cy("yt-remote-session-name")||"",c=g.cy("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Fra=function(a){a?(g.by("yt-remote-session-app",a.app),g.by("yt-remote-session-name",a.name)):(F5("yt-remote-session-app"),F5("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.E.call(this);
this.B=a;this.u=b;this.w=new g.Rs(this);g.H(this,this.w);this.w.M(b,"onCaptionsTrackListChanged",this.XI);this.w.M(b,"captionschanged",this.WH);this.w.M(b,"captionssettingschanged",this.bA);this.w.M(b,"videoplayerreset",this.Kn);this.w.M(b,"mdxautoplaycancel",this.NB);this.T=this.w.M(b,"onVolumeChange",this.yy);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.My,this);c.subscribe("remotePlayerChange",this.Gk,this);c.subscribe("remoteQueueChange",this.Kn,this);c.subscribe("autoplayUpNext",this.ny,
this);c.subscribe("previousNextChange",this.Jy,this);c.subscribe("nowAutoplaying",this.Fy,this);c.subscribe("autoplayDismissed",this.my,this);this.suggestion=null;this.H=new g.Ft(64);this.A=new g.J(this.Zz,500,this);g.H(this,this.A);this.C=new g.J(this.aA,1E3,this);g.H(this,this.C);this.K=new g6(this.DM,0,this);g.H(this,this.K);this.F={};this.U=new g.J(this.AA,1E3,this);g.H(this,this.U);this.J=new g.jl(this.sF,1E3,this);g.H(this,this.J);this.P=g.Ha;this.bA();this.Kn();this.Gk()},H8=function(a,b){var c=
a.B,d=a.u.getVideoData().lengthSeconds;
c.U=b||0;c.player.R("progresssync",b,d)},Nra=function(a){H8(a,0);
a.A.stop();I8(a,new g.Ft(64))},K8=function(a,b){if(J8(a)&&!a.G){var c=null;
b&&(c={style:a.u.getSubtitlesUserSettings()},g.ec(c,b));a.o.Qz(a.u.getVideoData(1).videoId,c);a.F=$7(a.o).o}},L8=function(a,b){var c=a.u.getPlaylist();
if(c){var d=c.Ua;var e=c.listId.toString()}c=a.u.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.Oe,A5(c));I8(a,new g.Ft(1))},Ora=function(a,b){if(b){var c=a.u.getOption("captions","tracklist",{PQ:1});
c&&c.length?(a.u.setOption("captions","track",b),a.G=!1):(a.u.loadModule("captions"),a.G=!0)}else a.u.setOption("captions","track",{})},J8=function(a){return $7(a.o).videoId==a.u.getVideoData(1).videoId},I8=function(a,b){a.C.stop();
var c=a.H;if(!g.Lt(c,b)){var d=g.R(b,2);d!=g.R(a.H,2)&&g.zS(a.u.app,d);a.H=b;Pra(a.B,c,b)}},M8=function(){g.T.call(this,{D:"div",
I:"ytp-mdx-popup-dialog",N:{role:"dialog"},L:[{D:"div",I:"ytp-mdx-popup-dialog-inner-content",L:[{D:"div",I:"ytp-mdx-popup-title",W:"Du bist nicht angemeldet"},{D:"div",I:"ytp-mdx-popup-description",W:"Videos, die du dir ansiehst, werden m\u00f6glicherweise zum TV-Wiedergabeverlauf hinzugef\u00fcgt und k\u00f6nnen sich damit auf deine TV-Empfehlungen auswirken. Melde dich auf einem Computer in YouTube an, um das zu vermeiden."},{D:"div",I:"ytp-mdx-privacy-popup-buttons",L:[{D:"button",X:["ytp-button",
"ytp-mdx-privacy-popup-cancel"],W:"Abbrechen"},{D:"button",X:["ytp-button","ytp-mdx-privacy-popup-confirm"],W:"Best\u00e4tigen"}]}]}]});this.w=new g.BL(this,250);g.H(this,this.w);this.F=this.u["ytp-mdx-privacy-popup-cancel"];this.M(this.F,"click",this.A);this.B=this.u["ytp-mdx-privacy-popup-confirm"];this.M(this.B,"click",this.C)},N8=function(a){g.T.call(this,{D:"div",
I:"ytp-remote",L:[{D:"div",I:"ytp-remote-display-status",L:[{D:"div",I:"ytp-remote-display-status-icon",L:[g.DL()]},{D:"div",I:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.w=new g.BL(this,250);g.H(this,this.w);this.A=a;this.M(a,"presentingplayerstatechange",this.B);Qra(this,g.rK(a))},Qra=function(a,b){if(3==a.A.getPresentingPlayerType()){var c={RECEIVER_NAME:a.A.getOption("remote","currentReceiver").name};
c=g.R(b,128)?g.hM("Fehler auf $RECEIVER_NAME",c):g.Mt(b)||g.R(b,4)?g.hM("Wiedergabe \u00fcber $RECEIVER_NAME",c):g.hM("Verbunden mit $RECEIVER_NAME",c);a.updateValue("statustext",c);a.w.show()}else a.w.hide()},O8=function(a,b){g.dO.call(this,"Wiedergeben auf",0,a,b);
this.w=a;this.F={};this.M(a,"onMdxReceiversChange",this.K);this.M(a,"presentingplayerstatechange",this.K);this.K()},P8=function(a){g.mP.call(this,a);
this.u={key:N5(),name:"Dieser Computer"};this.B=null;this.A=[];this.P=this.o=null;this.J=[this.u];this.w=this.u;this.F=new g.Ft(64);this.U=0;this.H=-1;this.C=null;if(!g.az(this.player.O())){a=this.player;var b=g.TC(a);b&&(b=b.qk())&&(b=new O8(a,b),g.H(this,b));b=new N8(a);g.H(this,b);g.KK(a,b.element,4);this.C=new M8;g.H(this,this.C);g.KK(a,this.C.element,4);this.K=!!u8()}this.G=null},Q8=function(a){a.G&&(a.player.removeEventListener("presentingplayerstatechange",a.G),a.G=null)},Pra=function(a,b,
c){a.F=c;
a.player.R("presentingplayerstatechange",new g.jD(c,b))},R8=function(a,b){if(b.key!=a.w.key)if(b.key==a.u.key)z8();
else{var c;(c=!g.P(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.ro("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.ro("SESSION_INDEX")&&!g.ro("LOGGED_IN")))||a.K||!a.C);if(c?0:g.oz(a.player.O())||"WEB_EMBEDDED_PLAYER"==a.player.O().deviceParams.c)g.Mt(g.rK(a.player))?a.player.pauseVideo():(a.G=(0,g.x)(a.zL,a),a.player.addEventListener("presentingplayerstatechange",a.G)),a.C&&a.C.w.show(),x8()||(E8=!0);a.w=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.wa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Oe,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=A5(c))&&(d.locationInfo=c);c=d}else c=null;r8("Connecting to: "+g.Bj(b));"cast-selector-receiver"==b.key?(t8(c||null),O7()?L7().setLaunchParams(c||null):J7("setLaunchParams called before ready.")):
!c&&C8()&&q8()==b.key?E5("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().Od(),(c=P5(c,b.key))&&A8(c,1))}},A6={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},z6={"'":"\\'"},Rra={},Wpa={FN:"atp",bQ:"ska",QP:"que",sP:"mus",aQ:"sus",FO:"dsp",XP:"seq"};
G5.prototype.gg=function(){var a=new G5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.w=this.w;a.u=this.u;a.o=this.o};
var Z5,S5="",cqa=a6("loadCastFramework")||a6("loadCastApplicationFramework"),gra=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Sa(g6,g.E);g.h=g6.prototype;g.h.OC=function(a){this.A=arguments;this.o=!1;this.Fa?this.w=(0,g.A)()+this.Xc:this.Fa=g.hl(this.B,this.Xc)};
g.h.stop=function(){this.Fa&&(g.u.clearTimeout(this.Fa),this.Fa=null);this.w=null;this.o=!1;this.A=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.A)))};
g.h.Y=function(){this.stop();g6.Ab.Y.call(this)};
g.h.PC=function(){this.w?(this.Fa=g.hl(this.B,this.w-(0,g.A)()),this.w=null):(this.Fa=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.A)))};i6.prototype.stringify=function(a){return g.u.JSON.stringify(a,void 0)};
i6.prototype.parse=function(a){return g.u.JSON.parse(a,void 0)};j6.prototype.o=null;j6.prototype.getOptions=function(){var a;(a=this.o)||(a={},l6(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Sa(k6,j6);S8=new k6;g.h=n6.prototype;g.h.gh=null;g.h.xe=!1;g.h.dj=null;g.h.Vs=null;g.h.Oi=null;g.h.hi=null;g.h.Zf=null;g.h.Hg=null;g.h.Ah=null;g.h.yc=null;g.h.nl=0;g.h.De=null;g.h.yo=null;g.h.qg=null;g.h.Sj=-1;g.h.Lz=!0;g.h.Sg=!1;g.h.eq=0;g.h.Qn=null;var u6={},s6={};g.h=n6.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.LL=function(a){a=a.target;var b=this.Qn;b&&3==R6(a)?b.Cm():this.IA(a)};
g.h.IA=function(a){try{if(a==this.yc)a:{var b=R6(this.yc),c=this.yc.C,d=this.yc.getStatus();if(g.Kd&&!g.od(10)||g.Md&&!g.nd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.hg&&!T6(this.yc))break a;this.Sg||4!=b||7==c||(8==c||0>=d?this.o.we(3):this.o.we(2));E6(this);var e=this.yc.getStatus();this.Sj=e;var f=T6(this.yc);(this.xe=200==e)?(4==b&&w6(this),this.B?(y6(this,b,f),g.hg&&this.xe&&3==b&&(this.ea.ha(this.u,"tick",this.FL),this.u.start())):v6(this,f),this.xe&&!this.Sg&&(4==b?this.o.Hn(this):(this.xe=
!1,r6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.qg=3,t6(13)):(this.qg=0,t6(14)),w6(this),x6(this))}}catch(k){this.yc&&T6(this.yc)}finally{}};
g.h.FL=function(){var a=R6(this.yc),b=T6(this.yc);this.nl<b.length&&(E6(this),y6(this,a,b),this.xe&&4!=a&&r6(this))};
g.h.bL=function(a){D6((0,g.x)(this.aL,this,a),0)};
g.h.aL=function(a){this.Sg||(E6(this),v6(this,a),r6(this))};
g.h.Ty=function(a){D6((0,g.x)(this.ZK,this,a),0)};
g.h.ZK=function(a){this.Sg||(w6(this),this.xe=a,this.o.Hn(this),this.o.we(4))};
g.h.cancel=function(){this.Sg=!0;w6(this)};
g.h.jL=function(){this.dj=null;var a=(0,g.A)();0<=a-this.Vs?(2!=this.hi&&this.o.we(3),w6(this),this.qg=2,t6(18),x6(this)):C6(this,this.Vs-a)};
g.h.getLastError=function(){return this.qg};g.h=I6.prototype;g.h.bq=null;g.h.Ed=null;g.h.Rn=!1;g.h.Qv=null;g.h.lm=null;g.h.Hq=null;g.h.cq=null;g.h.ie=null;g.h.Gf=-1;g.h.Rj=null;g.h.pj=null;g.h.connect=function(a){this.cq=a;a=J6(this.o,null,this.cq);t6(3);this.Qv=(0,g.A)();var b=this.o.G;null!=b?(this.Rj=b[0],(this.pj=b[1])?(this.ie=1,K6(this)):(this.ie=2,M6(this))):(z5(a,"MODE","init"),this.Ed=new n6(this,void 0,void 0,void 0),this.Ed.gh=this.bq,q6(this.Ed,a,!1,null,!0),this.ie=0)};
g.h.OB=function(a){if(a)this.ie=2,M6(this);else{t6(4);var b=this.o;b.Le=b.fg.Gf;$6(b,9)}a&&this.we(2)};
g.h.Bp=function(a){return this.o.Bp(a)};
g.h.abort=function(){this.Ed&&(this.Ed.cancel(),this.Ed=null);this.Gf=-1};
g.h.Pv=function(){return!1};
g.h.Ny=function(a,b){this.Gf=a.Sj;if(0==this.ie)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.Le=this.Gf;$6(c,2);return}this.Rj=c[0];this.pj=c[1]}else c=this.o,c.Le=this.Gf,$6(c,2);else if(2==this.ie)if(this.Rn)t6(7),this.Hq=(0,g.A)();else if("11111"==b){if(t6(6),this.Rn=!0,this.lm=(0,g.A)(),c=this.lm-this.Qv,!g.Kd||g.od(10)||500>c)this.Gf=200,this.Ed.cancel(),t6(12),L6(this.o,this,!0)}else t6(8),this.lm=this.Hq=(0,g.A)(),this.Rn=!1};
g.h.Hn=function(){this.Gf=this.Ed.Sj;if(this.Ed.xe)0==this.ie?this.pj?(this.ie=1,K6(this)):(this.ie=2,M6(this)):2==this.ie&&((!g.Kd||g.od(10)?!this.Rn:200>this.Hq-this.lm)?(t6(11),L6(this.o,this,!1)):(t6(12),L6(this.o,this,!0)));else{0==this.ie?t6(9):2==this.ie&&t6(10);var a=this.o;this.Ed.getLastError();a.Le=this.Gf;$6(a,2)}};
g.h.Wk=function(){return this.o.Wk()};
g.h.isActive=function(){return this.o.isActive()};
g.h.we=function(a){this.o.we(a)};g.Sa(N6,g.wk);var hqa=/^https?$/i,Sra=["POST","PUT"];g.h=N6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.A="";this.C=0;this.Z=b;this.T=!1;this.w=!0;this.o=this.P?m6(this.P):m6(S8);this.U=this.P?this.P.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.Rv,this);try{D5(S6(this,"Opening Xhr")),this.da=!0,this.o.open(b,String(a),!0),this.da=!1}catch(f){D5(S6(this,"Error opening Xhr: "+f.message));Q6(this,f);return}a=c||"";
var e=this.headers.clone();d&&Rpa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.fe(),gqa);c=g.u.FormData&&a instanceof g.u.FormData;!g.$a(Sra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.ba&&(this.o.responseType=this.ba);"withCredentials"in this.o&&this.o.withCredentials!==this.V&&(this.o.withCredentials=this.V);try{jqa(this),0<this.F&&(this.K=fqa(this.o),D5(S6(this,"Will abort after "+this.F+"ms if incomplete, xhr2 "+this.K)),this.K?(this.o.timeout=this.F,this.o.ontimeout=(0,g.x)(this.Sv,this)):this.J=g.hl(this.Sv,this.F,this)),D5(S6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){D5(S6(this,"Send error: "+f.message)),Q6(this,f)}};
g.h.Sv=function(){"undefined"!=typeof g.SZ&&this.o&&(this.A="Timed out after "+this.F+"ms, aborting",this.C=8,S6(this,this.A),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.w&&(S6(this,"Aborting"),this.w=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),P6(this))};
g.h.Y=function(){this.o&&(this.w&&(this.w=!1,this.B=!0,this.o.abort(),this.B=!1),P6(this,!0));N6.Ab.Y.call(this)};
g.h.Rv=function(){this.ia()||(this.da||this.G||this.B?iqa(this):this.ZJ())};
g.h.ZJ=function(){iqa(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<R6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.A?this.A:String(this.A)};g.h=U6.prototype;g.h.Cj=null;g.h.zd=null;g.h.Tb=null;g.h.Zp=null;g.h.nm=null;g.h.ku=null;g.h.Dm=null;g.h.Bk=0;g.h.qH=0;g.h.Uc=null;g.h.mg=null;g.h.uf=null;g.h.Xg=null;g.h.fg=null;g.h.wo=null;g.h.wi=-1;g.h.Aw=-1;g.h.Le=-1;g.h.Yh=0;g.h.Sh=0;g.h.Tg=8;var a7=new g.wk;g.Sa(lqa,g.Yj);g.Sa(mqa,g.Yj);g.Sa(nqa,g.Yj);g.h=U6.prototype;g.h.connect=function(a,b,c,d,e){t6(0);this.Zp=b;this.Cj=c||{};d&&void 0!==e&&(this.Cj.OSID=d,this.Cj.OAID=e);this.C?(D6((0,g.x)(this.Fu,this,a),100),rqa(this)):this.Fu(a)};
g.h.Fu=function(a){this.fg=new I6(this);this.fg.bq=null;this.fg.u=this.B;this.fg.connect(a)};
g.h.Pv=function(){return 0==this.o};
g.h.Sy=function(a){this.mg=null;uqa(this,a)};
g.h.Ry=function(){this.uf=null;this.Tb=new n6(this,this.w,"rpc",this.F);this.Tb.gh=null;this.Tb.eq=0;var a=this.ku.clone();x5(a,"RID","rpc");x5(a,"SID",this.w);x5(a,"CI",this.wo?"0":"1");x5(a,"AID",this.wi);V6(this,a);if(!g.Kd||g.od(10))x5(a,"TYPE","xmlhttp"),q6(this.Tb,a,!0,this.Dm,!1);else{x5(a,"TYPE","html");var b=this.Tb,c=!!this.Dm;b.hi=3;b.Zf=y5(a.clone());B6(b,c)}};
g.h.Ny=function(a,b){if(0!=this.o&&(this.Tb==a||this.zd==a))if(this.Le=a.Sj,this.zd==a&&3==this.o)if(7<this.Tg){try{var c=this.B.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.uf){if(this.Tb)if(this.Tb.Oi+3E3<this.zd.Oi)X6(this),this.Tb.cancel(),this.Tb=null;else break a;Z6(this);t6(19)}}else this.Aw=c[1],0<this.Aw-this.wi&&37500>c[2]&&this.wo&&0==this.Sh&&!this.Xg&&(this.Xg=D6((0,g.x)(this.SH,this),6E3));else $6(this,11)}else b!=Rra.dO.o&&$6(this,11);else if(this.Tb==a&&
X6(this),!g.xb(b)){c=this.B.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.wi=e[0];e=e[1];2==this.o?"c"==e[0]?(this.w=e[1],this.Dm=e[2],e=e[3],null!=e?this.Tg=e:this.Tg=6,this.o=3,this.Uc&&this.Uc.zu(),this.ku=J6(this,this.Wk()?this.Dm:null,this.Zp),vqa(this)):"stop"==e[0]&&$6(this,7):3==this.o&&("stop"==e[0]?$6(this,7):"noop"!=e[0]&&this.Uc&&this.Uc.yu(e),this.Sh=0)}}};
g.h.SH=function(){null!=this.Xg&&(this.Xg=null,this.Tb.cancel(),this.Tb=null,Z6(this),t6(20))};
g.h.Hn=function(a){if(this.Tb==a){X6(this);this.Tb=null;var b=2}else if(this.zd==a)this.zd=null,b=1;else return;this.Le=a.Sj;if(0!=this.o)if(a.xe)1==b?(b=(0,g.A)()-a.Oi,a7.dispatchEvent(new mqa(a7,a.Ah?a.Ah.length:0,b,this.Yh)),W6(this),this.A.length=0):vqa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Le)){if(d=1==b)this.zd||this.mg||1==this.o||2<=this.Yh?d=!1:(this.mg=D6((0,g.x)(this.Sy,this,a),wqa(this,this.Yh)),this.Yh++,d=!0);d=!(d||2==b&&Z6(this))}if(d)switch(c){case 1:$6(this,
5);break;case 4:$6(this,10);break;case 3:$6(this,6);break;case 7:$6(this,12);break;default:$6(this,2)}}};
g.h.iC=function(a){if(!g.$a(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.uM=function(a){a?t6(2):(t6(1),xqa(this,8))};
g.h.Bp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new N6;a.V=!1;return a};
g.h.isActive=function(){return!!this.Uc&&this.Uc.isActive(this)};
g.h.we=function(a){a7.dispatchEvent(new nqa(a7,a))};
g.h.Wk=function(){return!(!g.Kd||g.od(10))};
g.h=yqa.prototype;g.h.zu=function(){};
g.h.yu=function(){};
g.h.xu=function(){};
g.h.vp=function(){};
g.h.kv=function(){return{}};
g.h.isActive=function(){return!0};g.h=zqa.prototype;g.h.isEmpty=function(){return g.ab(this.o)&&g.ab(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.$a(this.o,a)||g.$a(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.Ana)(b,a);0<=c?(g.cb(b,c),b=!0):b=!1;return b||g.db(this.u,a)};
g.h.sd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Sa(b7,g.E);g.h=b7.prototype;g.h.SK=function(){this.Xc=Math.min(3E5,2*this.Xc);this.w();this.u&&this.start()};
g.h.start=function(){var a=this.Xc+15E3*Math.random();g.cn(this.o,a);this.u=(0,g.A)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Xc=5E3};g.Sa(c7,yqa);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.w.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.w.unsubscribe(a,b,c)};
g.h.Of=function(a){return this.w.hh(a)};
g.h.R=function(a,b){return this.w.R.apply(this.w,arguments)};
g.h.dispose=function(){this.ib||(this.ib=!0,g.Ei(this.w),Cqa(this),g.Ei(this.u),this.u=null)};
g.h.ia=function(){return this.ib};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.H="";this.u.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.K),e=this.o;e&&(e.Uc=null);d.Uc=this;this.o=d;e?this.o.connect(a,b,this.C,e.w,e.wi):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.F.push(c):d7(this)&&sqa(this.o,c)};
g.h.zu=function(){this.u.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)sqa(this.o,a[b])}this.R("handlerOpened")};
g.h.xu=function(a){var b=2==a&&401==this.o.Le;4==a||b||this.u.start();this.R("handlerError",a)};
g.h.vp=function(a){if(!this.u.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.kv=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.ec(a,this.B);return a};
g.h.yu=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),qqa(this.o)):this.R("handlerMessage",new Aqa(a[0],a[1]))};
g.h.VL=function(){this.u.isActive();var a=this.o,b=0;a.Tb&&b++;a.zd&&b++;0==b&&this.connect(this.B,this.A)};e7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.w=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var Kqa=(0,g.A)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Sa(m7,g.O);m7.prototype.Od=function(){return this.o};
m7.prototype.contains=function(a){return!!O5(this.o,a)};
m7.prototype.get=function(a){return a?P5(this.o,a):null};
m7.prototype.info=function(a){i7(this.F,a)};g.r(n7,g.O);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Fa)&&this.MA()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Fa)||(g.Fo(this.Fa),this.Fa=NaN)};
g.h.Y=function(){this.stop();g.O.prototype.Y.call(this)};
g.h.MA=function(){this.Fa=NaN;this.o=g.Bp(f7(this.C,"/pairing/get_screen"),{method:"POST",wb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.x)(this.ZM,this),onError:(0,g.x)(this.YM,this),Sd:(0,g.x)(this.aN,this)})};
g.h.ZM=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.w;c.name=this.A;this.R("pairingComplete",new H5(c))};
g.h.YM=function(a){this.o=null;a.status&&404==a.status?this.u>=Tra.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=Tra[this.u],this.Fa=g.zo((0,g.x)(this.MA,this),a),this.u++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.aN=function(){this.o=null;this.R("pairingFailed",Error("Server not responding"))};
var Tra=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.R("screenChange");!g.cy("yt-remote-lounge-token-expiration")&&Oqa(this);g.Fo(this.u);this.u=g.zo((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);Lqa(this,a);q7(this,!1);this.R("screenChange");b(a);a.token||Oqa(this)};
g.h.remove=function(a,b){var c=o7(this);Nqa(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.ro=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.Y=function(){g.Fo(this.u);p7.Ab.Y.call(this)};
g.h.ZC=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.F,"Missed "+b+" lounge tokens.")};
g.h.YC=function(a){i7(this.F,"Requesting lounge tokens failed: "+a)};g.r(s7,g.O);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.cy("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.A)()-144E5<a?0:a)?u7(this):(this.A=(0,g.A)()+3E5,g.by("yt-remote-fast-check-period",this.A),this.ds())};
g.h.isEmpty=function(){return g.Zb(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.Mb(this.o,function(c,d){return c&&!!P5(a,d)},this);
t7(this,b)};
g.h.Y=function(){g.Fo(this.w);this.w=NaN;this.u&&(this.u.abort(),this.u=null);g.O.prototype.Y.call(this)};
g.h.ds=function(){g.Fo(this.w);this.w=NaN;this.u&&this.u.abort();var a=Rqa(this);if(B5(a)){var b=f7(this.B,"/pairing/get_screen_availability");this.u=g7(this.B,b,{lounge_token:g.Sb(a).join(",")},(0,g.x)(this.vK,this,a),(0,g.x)(this.uK,this))}else t7(this,{}),u7(this)};
g.h.vK=function(a,b){this.u=null;var c=g.Sb(Rqa(this));if(g.rb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Nb("Changing Screen set during request."),this.ds()};
g.h.uK=function(a){this.Nb("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Nb=function(a){i7("OnlineScreenService",a)};g.Sa(v7,m7);g.h=v7.prototype;g.h.start=function(){this.w.start();this.u.start();this.o.length&&(this.R("screenChange"),this.u.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.w.add(a,b,c)};
g.h.remove=function(a,b,c){this.w.remove(a,b,c);this.u.update()};
g.h.ro=function(a,b,c,d){this.w.contains(a)?this.w.ro(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.F,a),d(Error(a)))};
g.h.Od=function(a){return a?this.o:g.fb(this.o,(0,g.Zd)(this.A,function(b){return!this.contains(b)},this))};
g.h.NA=function(){return(0,g.Zd)(this.Od(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.OA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.Ei(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Ei(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.cN=function(a,b,c,d){g.Bp(f7(this.C,"/pairing/get_screen"),{method:"POST",wb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new H5(f.screen||{});if(!k.name||Vqa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Vqa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Sd:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.Y=function(){g.Ei(this.w);g.Ei(this.u);v7.Ab.Y.call(this)};
g.h.gD=function(){Wqa(this);this.R("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Sa(y7,g.O);g.h=y7.prototype;g.h.Jn=function(a){this.w=a;this.R("sessionScreen",this.w)};
g.h.Rd=function(a){this.ia()||(a&&z7(this,""+a),this.w=null,this.R("sessionScreen",null))};
g.h.info=function(a){i7(this.U,a)};
g.h.QA=function(){return null};
g.h.ts=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.Y=function(){this.ts("");y7.Ab.Y.call(this)};g.Sa(A7,y7);g.h=A7.prototype;g.h.rs=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Yqa(this)};
g.h.xi=function(a){this.info("launchWithParams no-op for Cast: "+g.Bj(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.Rd()},this),(0,g.x)(function(){this.Rd(Error("Failed to stop receiver app."))},this)):this.Rd(Error("Stopping cast device witout session."))};
g.h.ts=g.Ha;g.h.Y=function(){this.info("disposeInternal");g.Fo(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.Ab.Y.call(this)};
g.h.uL=function(a,b){if(!this.ia())if(b){var c=h6(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Bj(c));switch(d){case "mdxSessionStatus":Xqa(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.Jv=function(a,b,c,d){Uqa(this.H,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.zo((0,g.x)(this.Jv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.QA=function(){return this.o};
g.h.dN=function(a){this.ia()||a||(z7(this,"Cast session died."),this.Rd())};g.Sa(B7,y7);g.h=B7.prototype;g.h.rs=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.xi=function(a){this.B=a;this.F()};
g.h.stop=function(){this.o();this.o=g.Ha;g.Fo(this.C);this.A?this.A.stop((0,g.x)(this.Rd,this,null),(0,g.x)(this.Rd,this,"Failed to stop DIAL device.")):this.Rd()};
g.h.Y=function(){this.o();this.o=g.Ha;g.Fo(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;B7.Ab.Y.call(this)};
g.h.gN=function(a){this.ia()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Ha,this.Rd())};
g.h.qq=function(a){this.J=N5();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,$qa(this));a(b);Zqa(this)}else this.F=(0,g.x)(function(){g.Fo(this.C);this.F=g.Ha;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,$qa(this));a(c);Zqa(this)},this),this.C=g.zo((0,g.x)(function(){this.F()},this),100)};
g.h.AD=function(a,b,c){Uqa(this.H,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.Jn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.qq(b,c)},this),(0,g.x)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.qq(b,c)},this))};g.Sa(C7,y7);C7.prototype.stop=function(){this.Rd()};
C7.prototype.rs=g.Ha;C7.prototype.xi=function(){g.Fo(this.o);this.o=NaN;var a=P5(this.H.Od(),this.u.label);a?this.Jn(a):this.Rd(Error("No such screen"))};
C7.prototype.Y=function(){g.Fo(this.o);this.o=NaN;C7.Ab.Y.call(this)};g.Sa(D7,g.O);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.eK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.Py,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.rI,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ia()||
(chrome.cast.addReceiverActionListener(this.A),Hqa(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.PA,this)),this.w=bra(this),chrome.cast.setCustomReceivers(this.w,g.Ha,(0,g.x)(function(k){this.Nb("Failed to set initial custom receivers: "+g.Bj(k))},this)),this.R("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(k){this.Nb("Failed to initialize API: "+g.Bj(k));
b(!1)},this))};
g.h.dM=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.w;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=P5(this.u.Od(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=ara(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.w.push(d),chrome.cast.setCustomReceivers(this.w,
g.Ha,(0,g.x)(function(e){this.Nb("Failed to set initial custom receivers: "+g.Bj(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.ts(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.eM=function(a){this.ia()?this.Nb("Setting connection data on disposed cast v2"):this.o?this.o.xi(a):this.Nb("Setting connection data without a session")};
g.h.fN=function(){this.ia()?this.Nb("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.Py,this),(0,g.x)(this.BK,this))};
g.h.Y=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.PA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);g.db(g.w("yt.mdx.remote.debug.handlers_")||[],Eqa);g.Ei(this.o);D7.Ab.Y.call(this)};
g.h.Nb=function(a){i7("Controller",a)};
g.h.Qy=function(a,b){this.o==a&&(b||G7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.aK=function(a,b){if(!this.ia())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.w&&this.R("yt-remote-cast2-session-change",this.o.w);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Nb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Nb("Stopping receiver w/o session: "+a.friendlyName)}else this.Nb("onReceiverAction_ called without receiver.")};
g.h.rI=function(a){if(this.ia())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Nb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Nb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.w)return E7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.o.w),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Nb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.AD,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.qq,b))};
g.h.Py=function(a){if(!this.ia()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Nb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=P5(this.u.Od(),c.label);d&&I5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ei(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.Qy,this,this.o)),this.o.xi(null));this.o.rs(a)}}};
g.h.eN=function(){return this.o?this.o.QA():null};
g.h.BK=function(a){this.ia()||(this.Nb("Failed to estabilish a session: "+g.Bj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.eK=function(a){E7("Receiver availability updated: "+a);if(!this.ia()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.R("yt-remote-cast2-availability-change",F7(this))}};
g.h.PA=function(){this.ia()||(this.w=bra(this),E7("Updating custom receivers: "+g.Bj(this.w)),chrome.cast.setCustomReceivers(this.w,g.Ha,(0,g.x)(function(){this.Nb("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.eM;D7.prototype.setConnectedScreenStatus=D7.prototype.dM;D7.prototype.stopSession=D7.prototype.fN;D7.prototype.getCastSession=D7.prototype.eN;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];R7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Me=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.C=a.playerTimeAt,this.A=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.H=a.loadedTime,this.w=a.liveIngestionTime,this.B=
!isNaN(this.w))};
R7.prototype.isAdPlaying=function(){return 1081==this.playerState};
R7.prototype.getDuration=function(){return this.B?this.G+T7(this):this.G};
R7.prototype.clone=function(){return new R7(X7(this))};g.r(Z7,g.O);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Ha,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ha,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ha,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.R("remotePlayerChange")}else a8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ha,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.R("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.w){if(c.volume!=a){var d=Math.round(a)/100;this.w.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Nb("failed to set receiver volume.")},this))}c.muted!=b&&this.w.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Nb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Qa(this.setVolume,a,b))};
g.h.Qz=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Bj(b.style),g.ec(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Qa(this.Qz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Bj(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.LA=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Qa(this.LA,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Qa(this.nextVideo,a,b))};
g.h.Nu=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.Nu)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.R("proxyStateChange",a,this.o)}g.O.prototype.dispose.call(this)};
g.h.Y=function(){ora(this);this.A=null;this.B.clear();Y7(this,null);g.O.prototype.Y.call(this)};
g.h.Ys=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.ab(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.XJ=function(a,b){this.R(a,b)};
g.h.YH=function(a){if(!a)this.Ek(null),Y7(this,null);else if(this.w.receiver.volume){a=this.w.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.Ek=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),pra(this),this.R("remotePlayerChange")};
g.h.XH=function(a){a?(pra(this),this.R("remotePlayerChange")):this.Ek(null)};
g.h.kI=function(){var a=lra();a&&Y7(this,a)};
g.h.Nb=function(a){i7("CP",a)};g.r(f8,g.O);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Sa.listId=c);this.Sa.videoId=d;this.Sa.index=k||0;this.Sa.state=3;U7(this.Sa,m);this.A="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.Bj(l));this.o.connect({method:"setPlaylist",
params:g.Bj(l)},a,V5())}else g8("Connecting without params"),this.o.connect({},a,V5());rra(this)};
g.h.dispose=function(){this.ia()||(this.R("beforeDispose"),h8(this,3));g.O.prototype.dispose.call(this)};
g.h.Y=function(){i8(this);k8(this);j8(this);g.Fo(this.F);this.F=NaN;g.Fo(this.G);this.G=NaN;this.w=null;g.ar(this.U);this.U.length=0;this.o.dispose();g.O.prototype.Y.call(this);this.A=this.C=this.u=this.Sa=this.o=null};
g.h.SC=function(){this.Wh(2)};
g.h.cI=function(){g8("Channel opened");this.K&&(this.K=!1,j8(this),this.J=g.zo((0,g.x)(function(){g8("Timing out waiting for a screen.");this.Wh(1)},this),15E3));
aqa(Bqa(this.o),this.P)};
g.h.ZH=function(){g8("Channel closed");isNaN(this.B)?Y5(!0):Y5();this.dispose()};
g.h.aI=function(a){Y5();isNaN(this.Mj())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.K=!0,g8("Channel error: "+a+" with reconnection in "+this.Mj()+" ms"),h8(this,2))};
g.h.bI=function(a){a.params?g8("Received: action="+a.action+", params="+g.Bj(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=h6(a.params.devices);this.u=(0,g.ie)(a,function(c){return new G5(c)});
a=!!g.Xa(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
ura(this,a);break;case "loungeScreenDisconnected":g.eb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
ura(this,!1);break;case "remoteConnected":var b=new G5(h6(a.params.device));g.Xa(this.u,function(c){return b?c.id==b.id:!1})||Opa(this.u,b);
break;case "remoteDisconnected":b=new G5(h6(a.params.device));g.eb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":wra(this,a);break;case "nowPlaying":yra(this,a);break;case "onStateChange":xra(this,a);break;case "onAdStateChange":zra(this,a);break;case "onVolumeChanged":Ara(this,a);break;case "onSubtitlesTrackChanged":vra(this,a);break;case "nowAutoplaying":Bra(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.R("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":Cra(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.SL=function(){if(this.w){var a=this.w;this.w=null;this.Sa.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.HC=function(){var a=3;this.ia()||(a=0,isNaN(this.Mj())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.Wh=function(a){g8("Disconnecting with "+a);i8(this);this.R("beforeDisconnect",a);1==a&&Y5();Cqa(this.o,a);this.dispose()};
g.h.GC=function(){var a=this.Sa;this.w&&(a=this.Sa.clone(),W7(a,this.w,a.index));return X7(a)};
g.h.fM=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Sa.videoId&&(this.w=b.videoId,g.Fo(this.F),this.F=g.zo((0,g.x)(this.SL,this),5E3));var c=[];this.Sa.listId==b.listId&&this.Sa.videoId==b.videoId&&this.Sa.index==b.index||c.push("remoteQueueChange");this.Sa.playerState==b.playerState&&this.Sa.volume==b.volume&&this.Sa.muted==b.muted&&V7(this.Sa)==V7(b)&&g.Bj(this.Sa.o)==g.Bj(b.o)||c.push("remotePlayerChange");this.Sa.reset(a);(0,g.z)(c,function(d){this.R(d)},this)};
g.h.Hv=function(){var a=this.o.C.id,b=g.Xa(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Mj=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.A)():NaN};
g.h.vC=function(){return this.A||"UNSUPPORTED"};
g.h.wC=function(){return this.C||""};
g.h.XM=function(){if(!isNaN(this.Mj())){var a=this.o.u;g.dn(a.o);a.start()}};
g.h.aM=function(a,b){l8(this,a,b);tra(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.Of;f8.prototype.getProxyState=f8.prototype.HC;f8.prototype.disconnect=f8.prototype.Wh;f8.prototype.getPlayerContextData=f8.prototype.GC;f8.prototype.setPlayerContextData=f8.prototype.fM;f8.prototype.getOtherConnectedRemoteId=f8.prototype.Hv;f8.prototype.getReconnectTimeout=f8.prototype.Mj;f8.prototype.getAutoplayMode=f8.prototype.vC;f8.prototype.getAutoplayVideoId=f8.prototype.wC;f8.prototype.reconnect=f8.prototype.XM;
f8.prototype.sendMessage=f8.prototype.aM;g.r(m8,m7);g.h=m8.prototype;g.h.Od=function(a){return this.Wc.$_gs(a)};
g.h.contains=function(a){return!!this.Wc.$_c(a)};
g.h.get=function(a){return this.Wc.$_g(a)};
g.h.start=function(){this.Wc.$_st()};
g.h.add=function(a,b,c){this.Wc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Wc.$_r(a,b,c)};
g.h.ro=function(a,b,c,d){this.Wc.$_un(a,b,c,d)};
g.h.Y=function(){for(var a=0,b=this.u.length;a<b;++a)this.Wc.$_ubk(this.u[a]);this.u.length=0;this.Wc=null;m7.prototype.Y.call(this)};
g.h.bN=function(){this.R("screenChange")};
g.h.BJ=function(){this.R("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.cN;v7.prototype.$_gsppc=v7.prototype.OA;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.ro;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.Od;v7.prototype.$_gos=v7.prototype.NA;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.Of;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.E);g.h=G8.prototype;
g.h.Y=function(){g.E.prototype.Y.call(this);this.A.stop();this.C.stop();this.K.stop();this.P();this.o.unsubscribe("proxyStateChange",this.My,this);this.o.unsubscribe("remotePlayerChange",this.Gk,this);this.o.unsubscribe("remoteQueueChange",this.Kn,this);this.o.unsubscribe("autoplayUpNext",this.ny,this);this.o.unsubscribe("previousNextChange",this.Jy,this);this.o.unsubscribe("nowAutoplaying",this.Fy,this);this.o.unsubscribe("autoplayDismissed",this.my,this);this.o=this.B=null};
g.h.ix=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(J8(this)){if(!$7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==$7(this.o).playerState?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.Cm(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.u.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,c)}};
g.h.WH=function(a){this.K.OC(a)};
g.h.DM=function(a){this.ix("control_subtitles_set_track",g.Zb(a)?null:a)};
g.h.bA=function(){var a=this.u.getOption("captions","track");g.Zb(a)||K8(this,a)};
g.h.yy=function(a){if(J8(this)){this.o.unsubscribe("remotePlayerChange",this.Gk,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.U.start();this.o.subscribe("remotePlayerChange",this.Gk,this)}};
g.h.XI=function(){g.Zb(this.F)||Ora(this,this.F);this.G=!1};
g.h.My=function(a,b){this.C.stop();2==b&&this.aA()};
g.h.Gk=function(){if(J8(this)){this.A.stop();var a=$7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.H=1;break;case 1082:case 1083:this.B.H=0;break;default:this.B.H=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.Ft(8));this.Zz();break;case 1085:case 3:I8(this,new g.Ft(9));break;case 1083:case 0:I8(this,new g.Ft(2));this.J.stop();H8(this,this.u.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.Ft(4));break;case 2:I8(this,new g.Ft(4));H8(this,V7(a));
break;case -1:I8(this,new g.Ft(64));break;case -1E3:I8(this,new g.Ft(128,{errorCode:"mdx.remoteerror",errorMessage:"Dieses Video ist nicht f\u00fcr die Remote-Wiedergabe verf\u00fcgbar."}))}a=$7(this.o).o;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.F=a,Ora(this,a));a=$7(this.o);-1==a.volume||Math.round(this.u.getVolume())==a.volume&&this.u.isMuted()==a.muted||this.U.isActive()||this.AA()}else Nra(this)};
g.h.Jy=function(){this.u.R("mdxpreviousnextchange")};
g.h.Kn=function(){J8(this)||Nra(this)};
g.h.NB=function(){this.o.Nu()};
g.h.ny=function(a){a&&!g.P(this.u.O().experiments,"disable_legacy_desktop_remote_queue")&&(a=g.Bp("/watch_queue_ajax",{method:"GET",ud:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.dL,this)}))&&(this.P=(0,g.x)(a.abort,a))};
g.h.dL=function(a,b){var c=new g.NB(this.u.O(),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.u.R("mdxautoplayupnext",c)};
g.h.Fy=function(a){isNaN(a)||this.u.R("mdxnowautoplaying",a)};
g.h.my=function(){this.u.R("mdxautoplaycanceled")};
g.h.sF=function(a,b){-1==$7(this.o).playerState?L8(this,a):b&&this.o.seekTo(a)};
g.h.AA=function(){if(J8(this)){var a=$7(this.o);this.w.Wa(this.T);a.muted?this.u.mute():this.u.unMute();this.u.setVolume(a.volume);this.T=this.w.M(this.u,"onVolumeChange",this.yy)}};
g.h.Zz=function(){this.A.stop();if(!this.o.ia()){var a=$7(this.o);1==a.playerState&&I8(this,new g.Ft(8));H8(this,V7(a));this.A.start()}};
g.h.aA=function(){this.C.stop();this.A.stop();var a=this.o.A.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.C.start()};g.r(M8,g.T);M8.prototype.A=function(){E5("mdx-privacy-popup-cancel");this.w.hide()};
M8.prototype.C=function(){E5("mdx-privacy-popup-confirm");this.w.hide()};g.r(N8,g.T);N8.prototype.B=function(a){Qra(this,a.state)};g.r(O8,g.dO);O8.prototype.K=function(){var a=this.w.getOption("remote","receivers");a&&1<a.length&&!this.w.getOption("remote","quickCast")?(this.F=g.ub(a,this.C,this),g.fO(this,(0,g.ie)(a,this.C)),a=this.w.getOption("remote","currentReceiver"),this.le(this.C(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.C=function(a){return a.key};
O8.prototype.ue=function(a){return"cast-selector-receiver"==a?"Streamen\u2026":this.F[a].name};
O8.prototype.Pc=function(a){g.dO.prototype.Pc.call(this,a);this.w.setOption("remote","currentReceiver",this.F[a]);this.A.nb()};g.r(P8,g.mP);g.h=P8.prototype;
g.h.create=function(){Hra(g.Sy(this.player.O()));this.A.push(g.Ko("yt-remote-before-disconnect",this.TH,this));this.A.push(g.Ko("yt-remote-connection-change",this.fK,this));this.A.push(g.Ko("yt-remote-receiver-availability-change",this.Ky,this));this.A.push(g.Ko("yt-remote-auto-connect",this.dK,this));this.A.push(g.Ko("yt-remote-receiver-resumed",this.cK,this));this.A.push(g.Ko("mdx-privacy-popup-confirm",this.IL,this));this.A.push(g.Ko("mdx-privacy-popup-cancel",this.HL,this));this.Ky()};
g.h.load=function(){this.player.cancelPlayback();g.mP.prototype.load.call(this);this.B=new G8(this,this.player,this.o);var a=(a=Mra())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!=a&&(this.U=a||0,this.player.R("progresssync",a,void 0));Pra(this,this.F,this.F);g.FS(this.player.app,6)};
g.h.unload=function(){this.player.R("mdxautoplaycanceled");this.w=this.u;g.Fi(this.B,this.o);this.o=this.B=null;g.mP.prototype.unload.call(this);g.FS(this.player.app,5);Q8(this)};
g.h.Y=function(){g.Lo(this.A);g.mP.prototype.Y.call(this)};
g.h.nk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.ix.apply(this.B,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.H};
g.h.JC=function(){return this.loaded?this.B.suggestion:null};
g.h.Me=function(){return this.o?$7(this.o).Me:!1};
g.h.hasNext=function(){return this.o?$7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.U};
g.h.getProgressState=function(){var a=$7(this.o),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.sc():!a.isAdPlaying()&&this.player.sc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.B?a.w+T7(a):a.w,isAtLiveHead:1>=(a.B?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.H,seekableEnd:a.B?a.u+T7(a):a.u,seekableStart:0<a.A?a.A+T7(a):
a.A}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.gF=function(){this.o&&this.o.LA()};
g.h.TH=function(a){1==a&&(this.P=this.o?$7(this.o):null)};
g.h.fK=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.w;this.loaded&&this.unload();this.o=a;this.P=null;b.key!=this.u.key&&(this.w=b,this.load())}else g.Ei(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.P)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.R("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Ky=function(){this.J=[this.u].concat(Jra());var a=y8()||this.u;R8(this,a);this.player.la("onMdxReceiversChange")};
g.h.zL=function(a){!this.K&&g.lD(a,8)&&(this.player.pauseVideo(),Q8(this))};
g.h.dK=function(){var a=y8();R8(this,a)};
g.h.cK=function(){this.w=y8()};
g.h.IL=function(){this.K=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.HL=function(){this.K=!1;Q8(this);R8(this,this.u);this.w=this.u;E8=!1;F8=null;this.player.playVideo()};
g.h.Ac=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.J;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?P7():R8(this,b)),this.loaded?this.w:this.u;case "quickCast":return 2==this.J.length&&"cast-selector-receiver"==this.J[1].key?(b&&P7(),!0):!1}};
g.h.hF=function(){d8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.ff=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.BP.remote=P8;})(_yt_player);
